# Generated by Django 3.1 on 2020-08-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
                ('github_url', models.CharField(max_length=500)),
                ('screenshot', models.CharField(max_length=500)),
                ('technologies_used', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
