# Generated by Django 3.1 on 2020-08-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalprojectsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='project_url',
        ),
    ]
